from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class FileInfo(BaseModel):
    filename: str
    status: Optional[str] = None
    additions: Optional[int] = None
    deletions: Optional[int] = None
    changes: Optional[int] = None
    patch: Optional[str] = None  # unified diff


class ReviewPayload(BaseModel):
    kind: str  # "review" or "review_comment"

    review_body: Optional[str] = None
    review_state: Optional[str] = None

    comment_body: Optional[str] = None
    comment_path: Optional[str] = None
    comment_diff_hunk: Optional[str] = None
    comment_position: Optional[int] = None
    comment_id: Optional[int] = None

    reviewer_login: Optional[str] = None
    pr_number: int
    pr_title: Optional[str] = None
    pr_body: Optional[str] = None
    pr_author_login: Optional[str] = None
    repo_full_name: str
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None

    files: Optional[List[FileInfo]] = None


class BackendResponse(BaseModel):
    comment: str


def extract_before_after(patch: str):
    """
    Very simple parser:
      - lines starting with '-' are "before"
      - lines starting with '+' are "after"
      - we ignore context lines (' '), hunk headers ('@@'), etc.
    """
    before, after = [], []
    for line in patch.splitlines():
        if line.startswith('@@') or line.startswith('diff ') or line.startswith('index '):
            continue
        if line.startswith('-'):
            before.append(line[1:])
        elif line.startswith('+'):
            after.append(line[1:])
        # context lines ' ' are skipped
    return before, after


@app.post("/analyze-review", response_model=BackendResponse)
async def analyze_review(payload: ReviewPayload):
    files = payload.files or []
    num_files = len(files)

    if payload.kind == "review":
        source_desc = f"full review (**{payload.review_state}**)"
        text = payload.review_body or ""
    else:
        source_desc = (
            f"inline comment on `{payload.comment_path}` "
            f"(position {payload.comment_position})"
        )
        text = payload.comment_body or ""

    header = (
        f"I received a **{payload.kind}** ({source_desc}) on PR "
        f"**#{payload.pr_number} – {payload.pr_title}** in `{payload.repo_full_name}`.\n\n"
        f"**Reviewer:** `{payload.reviewer_login}`\n\n"
        f"**Original text:**\n\n> {text.replace('\n', '\n> ')}\n\n"
    )

    files_part = f"I see **{num_files}** changed file(s).\n\n"

    # Show proof of before/after for up to 1–2 files to avoid huge comments
    for f in files[:2]:
        if not f.patch:
            continue
        before_lines, after_lines = extract_before_after(f.patch)
        files_part += f"### File: `{f.filename}`\n"
        files_part += "**Before (changed lines):**\n```diff\n"
        for line in before_lines[:10]:
            files_part += f"- {line}\n"
        files_part += "```\n\n"

        files_part += "**After (changed lines):**\n```diff\n"
        for line in after_lines[:10]:
            files_part += f"+ {line}\n"
        files_part += "```\n\n"

    footer = "_(auto-generated by ContextWizard backend – showing before/after of changed code)_"

    return BackendResponse(comment=header + files_part + footer)
