# backend/main.py
from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class FileInfo(BaseModel):
    filename: str
    status: Optional[str] = None
    additions: Optional[int] = None
    deletions: Optional[int] = None
    changes: Optional[int] = None
    patch: Optional[str] = None  # unified diff string


class ReviewCommentInfo(BaseModel):
    id: int
    body: str
    path: Optional[str] = None
    diff_hunk: Optional[str] = None
    position: Optional[int] = None
    line: Optional[int] = None
    original_line: Optional[int] = None
    user_login: Optional[str] = None


class ReviewPayload(BaseModel):
    kind: str  # "review" or "review_comment"

    # review-level fields
    review_body: Optional[str] = None
    review_state: Optional[str] = None

    # inline-comment-level fields
    comment_body: Optional[str] = None
    comment_path: Optional[str] = None
    comment_diff_hunk: Optional[str] = None
    comment_position: Optional[int] = None
    comment_id: Optional[int] = None

    reviewer_login: Optional[str] = None
    pr_number: int
    pr_title: Optional[str] = None
    pr_body: Optional[str] = None
    pr_author_login: Optional[str] = None
    repo_full_name: str
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None

    files: Optional[List[FileInfo]] = None

    # 🔥 NEW: all inline comments that belong to this finished review
    review_comments: Optional[List[ReviewCommentInfo]] = None


class BackendResponse(BaseModel):
    comment: str


@app.post("/analyze-review", response_model=BackendResponse)
async def analyze_review(payload: ReviewPayload):
    # Debug: print full JSON payload to server stderr
    import json, sys

    print("==== Incoming payload ====", file=sys.stderr)
    print(json.dumps(payload.dict(), indent=2), file=sys.stderr)
    print("==========================", file=sys.stderr)

    files = payload.files or []
    num_files = len(files)

    # figure out where the text came from
    if payload.kind == "review":
        source_desc = f"full review (**{payload.review_state}**)"
        text = payload.review_body or ""
    else:
        source_desc = (
            f"inline comment on `{payload.comment_path}` "
            f"(position {payload.comment_position})"
        )
        text = payload.comment_body or ""

    header = (
        f"I received a **{payload.kind}** ({source_desc}) on PR "
        f"**#{payload.pr_number} – {payload.pr_title}** in `{payload.repo_full_name}`.\n\n"
        f"**Reviewer:** `{payload.reviewer_login}`\n\n"
        f"**Original text:**\n\n> {text.replace('\n', '\n> ')}\n\n"
        f"I see **{num_files} changed file(s)**.\n\n"
    )

    snippet = ""

    # 🔎 If this is a finished review, show all its inline comments
    if payload.kind == "review" and payload.review_comments:
        snippet += f"### Inline comments that belong to this review ({len(payload.review_comments)}):\n\n"
        for c in payload.review_comments[:10]:  # limit to first 10 for safety
            snippet += f"- Comment `{c.id}` by `{c.user_login}` on `{c.path}` (line {c.line or c.position}):\n"
            snippet += f"  > { (c.body or '').replace(chr(10), '\\n  > ') }\n\n"
            if c.diff_hunk:
                snippet += "  Diff hunk:\n\n```diff\n"
                snippet += c.diff_hunk[:500]  # truncate long hunks
                snippet += "\n```\n\n"

    footer = "_(auto-generated by ContextWizard backend – debug mode: knows all inline comments for this finished review)_"

    return BackendResponse(comment=header + snippet + footer)
